"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "matcher",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "matcher.middleware.PurgeExpiredMiddleware",
    "matcher.middleware.NoStoreMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---- Resume Job Matcher settings ----
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

RESUME_TTL_SECONDS = int(os.environ.get("RESUME_TTL_SECONDS", 3600))   # 1 hour
RESUME_MAX_BYTES = 5 * 1024 * 1024
RESUME_PURGE_INTERVAL = 60            # background purge cadence (seconds)
RESUME_START_PURGER = os.environ.get("RESUME_START_PURGER", "1") == "1"
COMPANIES_FILE = BASE_DIR / "companies.yaml"
JOB_FETCH_TIMEOUT = int(os.environ.get("JOB_FETCH_TIMEOUT", 6))
JOB_CACHE_SECONDS = 1800
JOB_ERROR_CACHE_SECONDS = int(os.environ.get("JOB_ERROR_CACHE_SECONDS", 3600))  # remember dead sources for 1 h
JOB_FETCH_WORKERS = int(os.environ.get("JOB_FETCH_WORKERS", 100))                # parallel career-site fetches
JOB_SEARCH_DEADLINE = int(os.environ.get("JOB_SEARCH_DEADLINE", 30))            # max seconds a COLD search waits for all sources

# No third-party job-board API keys are required.

CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("DJANGO_CSRF_ORIGINS", "").split(",") if o]
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_AGE = 60 * 60 * 2

# Shared on-disk cache: all web workers reuse the same fetched job lists
# MAX_ENTRIES matters: Django's default is 300 and it then silently DELETES a third of the cache, which threw away
# freshly fetched career-site data (200+ sources + job details) and made every search re-download everything.
CACHES = {"default": {"BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
                      "LOCATION": BASE_DIR / ".cache",
                      "OPTIONS": {"MAX_ENTRIES": 50000, "CULL_FREQUENCY": 10}}}
RESUME_SYNC_SEARCH = False      # True = run the job search inside the request (used by tests)
JOB_DETAIL_LIMIT = 60           # fetch full descriptions only for this many title-relevant, newest jobs

# How experience is totalled from the dates in the Experience section:
#   "worked" = months actually worked, each role counted first month..last/present month inclusive, overlaps once
#   "span"   = first role's start month .. latest end month (gaps between jobs count too)
# A number the candidate wrote themselves ("3 years of experience") always wins over both.
EXPERIENCE_METHOD = os.environ.get("EXPERIENCE_METHOD", "worked")
JOB_STALE_SECONDS = int(os.environ.get("JOB_STALE_SECONDS", 86400))            # keep old job lists a day to serve instantly while refreshing
JOB_EMPTY_CACHE_SECONDS = int(os.environ.get("JOB_EMPTY_CACHE_SECONDS", 21600))  # sites that expose no job data: re-check every 6 h
JOB_START_WARMER = os.environ.get("JOB_START_WARMER", "1") == "1"               # background thread keeps every source fresh
JOB_WARM_INTERVAL = int(os.environ.get("JOB_WARM_INTERVAL", 1500))              # seconds between warm-up rounds

# ---- IT-park listing readers (Infopark / Technopark / Cyberpark) ----
PARK_RENDER = os.environ.get("PARK_RENDER", "1") == "1"            # on by default: headless-browser fallback for JavaScript-only park pages (used only if Playwright is installed)
PARK_MAX_PAGES = int(os.environ.get("PARK_MAX_PAGES", 12))          # follow pagination up to this many pages per park
PARK_EMPTY_CACHE_SECONDS = int(os.environ.get("PARK_EMPTY_CACHE_SECONDS", 300))   # a park that returned 0 jobs is retried after 5 min
PARK_INSECURE_FALLBACK = os.environ.get("PARK_INSECURE_FALLBACK", "1") == "1"   # read public park pages whose TLS certificate is broken


# ---- Privacy: resume lifetime ----
# The page pings every ~30 s while it is open. If pings stop (tab closed, browser force-stopped, phone locked, network gone)
# the resume is deleted RESUME_IDLE_SECONDS later - by the next request to the site, or by the scheduled purge task.
# RESUME_TTL_SECONDS above stays as the absolute maximum life. Set RESUME_IDLE_SECONDS=0 to disable the heartbeat rule.
RESUME_IDLE_SECONDS = int(os.environ.get("RESUME_IDLE_SECONDS", 180))
RESUME_LEAVE_SECONDS = int(os.environ.get("RESUME_LEAVE_SECONDS", 45))      # countdown started when a tab is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True      # the "owner" cookie dies with the browser
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# ---- Job data source ----
# "live"     = scrape career sites at search time (your PC)
# "snapshot" = read data/jobs_snapshot.json.gz built by GitHub Actions (PythonAnywhere free: no outgoing scraping)
JOB_SOURCE = os.environ.get("JOB_SOURCE", "live")
JOB_SNAPSHOT_FILE = Path(os.environ.get("JOB_SNAPSHOT_FILE", BASE_DIR / "data" / "jobs_snapshot.json.gz"))
if JOB_SOURCE == "snapshot":
    JOB_START_WARMER = False                # nothing to warm; the site must not try to reach career sites
