# Generated by Django 5.2.17 on 2026-10-04 14:22

import django.db.models.deletion
import matcher.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_session", models.CharField(db_index=True, max_length=64)),
                ("file", models.FileField(upload_to="resumes/")),
                ("original_name", models.CharField(max_length=255)),
                ("raw_text", models.TextField(blank=True)),
                ("parsed", models.JSONField(default=dict)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, default=matcher.models._expiry),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_key", models.CharField(max_length=300)),
                ("file", models.FileField(upload_to="generated/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated",
                        to="matcher.resume",
                    ),
                ),
            ],
        ),
    ]
